import os
import numpy as np
import pandas as pd
from scipy.interpolate import interp1d
import matplotlib.pyplot as plt

def main():
    # ==========================================
    # 1. CONFIGURATION & FILE PATHS
    # ==========================================
    MOVIE_NAME = 'Chatter'
    
    target_params = ['IntenseEmotion', 'Predictable', 'Alert', 'Attention', 'Heartrate']
    param_colors = ['blue', 'green', 'purple', 'darkorange', 'cyan']
    
    base_dir = r'C:\Users\ragha\Desktop\Honors Work Arousal Analysis\01_Aim_1_fMRI_to_ARS'
    
    pred_path = os.path.join(base_dir, '05_extracted_features', MOVIE_NAME, f'Predicted_Arousal_{MOVIE_NAME}.npy')
    data_dir = r'C:\Users\ragha\Desktop\Honors Work Arousal Analysis\data\annotation_files'
    emotion_path = os.path.join(data_dir, f'Annot_{MOVIE_NAME}_stim.tsv')
    
    output_dir = os.path.join(base_dir, '05_extracted_features', MOVIE_NAME, 'Behavioral_Comparisons')
    os.makedirs(output_dir, exist_ok=True)
    
    output_plot_path = os.path.join(output_dir, f'{MOVIE_NAME}_Annotations_Only_Plot.png')

    # ==========================================
    # 2. LOAD DATA
    # ==========================================
    print(f"--- Loading Data ---")
    try:
        predicted_arousal = np.load(pred_path)
    except FileNotFoundError:
        print(f"[!] Error: Could not find predictions at {pred_path}")
        return
        
    num_subjects = predicted_arousal.shape[0]
    mean_predicted_arousal = np.mean(predicted_arousal, axis=0)

    json_columns = [
        "Standards", "PleasantSelf", "SocialNorms", "PleasantOther", "GoalsOther",
        "Controlled", "Predictable", "Suddenly", "Agent", "Urgency", "Lips",
        "Tears", "Eyebrows", "Smile", "Frown", "Stop", "Undo", "Repeat",
        "Oppose", "Attention", "Tackle", "Command", "Support", "Move", "Care",
        "Bad", "Good", "Calm", "Strong", "IntenseEmotion", "Alert", "AtEase",
        "Muscle", "Heartrate", "Throat", "Stomach", "Warm", "Anger", "Guilt",
        "WarmHeartedness", "Disgust", "Happiness", "Fear", "Regard", "Anxiety",
        "Satisfaction", "Pride", "Surprise", "Love", "Sad"
    ]

    try:
        emotion_df = pd.read_csv(emotion_path, sep='\t', header=None, names=json_columns)
    except FileNotFoundError:
        print(f"[!] Error: Could not find TSV at {emotion_path}")
        return

    # ==========================================
    # 3. TEMPORAL ALIGNMENT TIMELINES
    # ==========================================
    tr_duration = 1.3
    total_scan_trs = 464 
    window_size = 45

    all_tr_times = np.arange(total_scan_trs) * tr_duration
    pred_window_centers_tr = np.arange(predicted_arousal.shape[1]) + (window_size / 2.0)
    pred_times_sec = pred_window_centers_tr * tr_duration
    
    annot_start_sec = 90.0
    movie_duration_sec = len(emotion_df['IntenseEmotion'].values)
    annot_times_sec = np.arange(movie_duration_sec) + annot_start_sec

    movie_tr_mask = (all_tr_times >= annot_start_sec) & (all_tr_times <= (annot_start_sec + movie_duration_sec))
    movie_tr_times = all_tr_times[movie_tr_mask]
    movie_tr_indices = movie_tr_times / tr_duration

    # ==========================================
    # 4. THE GHOST PLOT (STEALING THE SCALES)
    # ==========================================
    print("--- Generating Plot ---")
    plt.figure(figsize=(15, 8)) 

    def normalize_array(arr):
        return (arr - np.mean(arr)) / (np.std(arr) + 1e-8)

    # A. Draw the predictions exactly as they were in the original script
    for subj in range(num_subjects):
        subj_pred_interpolator = interp1d(pred_times_sec, predicted_arousal[subj, :], kind='linear', bounds_error=False, fill_value='extrapolate')
        plt.plot(movie_tr_indices, normalize_array(subj_pred_interpolator(movie_tr_times)))

    # B. Draw the mean prediction
    pred_interpolator = interp1d(pred_times_sec, mean_predicted_arousal, kind='linear', bounds_error=False, fill_value='extrapolate')
    plt.plot(movie_tr_indices, normalize_array(pred_interpolator(movie_tr_times)))

    # C. Draw the annotations
    for param in target_params:
        if param in emotion_df.columns:
            annot_interpolator = interp1d(annot_times_sec, emotion_df[param].values, kind='linear', bounds_error=False, fill_value='extrapolate')
            plt.plot(movie_tr_indices, annot_interpolator(movie_tr_times))

    # D. Capture the exact axes limits generated by the full dataset
    saved_xlim = plt.xlim()
    saved_ylim = plt.ylim()

    # E. Wipe the entire canvas clean (deletes all drawn lines)
    plt.cla()

    # ==========================================
    # 5. CONSTRUCT THE FINAL VISUALIZATION
    # ==========================================
    
    # Immediately force the blank canvas to adopt the exact stolen dimensions
    plt.xlim(saved_xlim)
    plt.ylim(saved_ylim)

    # Plot ONLY the behavioral annotations
    for param, color in zip(target_params, param_colors):
        if param in emotion_df.columns:
            param_1hz = emotion_df[param].values
            
            annot_interpolator = interp1d(annot_times_sec, param_1hz, kind='linear', bounds_error=False, fill_value='extrapolate')
            param_at_trs = annot_interpolator(movie_tr_times)
            
            plt.plot(movie_tr_indices, param_at_trs, color=color, linewidth=2.5, zorder=5, label=f'{param} (Annotation)')

    # Formatting & Display
    plt.title(f'Dynamic Overlay: Key Behavioral Annotations ({MOVIE_NAME})', fontsize=14, fontweight='bold')
    plt.xlabel('Time(s)', fontsize=12)
    plt.ylabel('Amplitude (Z-Score)', fontsize=12)
    
    plt.legend(loc='upper center', bbox_to_anchor=(0.5, -0.12), ncol=3, borderaxespad=0.)
    plt.grid(True, linestyle='--', alpha=0.5)
    
    plt.tight_layout()
    plt.savefig(output_plot_path, dpi=600, bbox_inches='tight')
    plt.show()
    
    print(f"-> Successfully saved structurally locked annotations plot to: {output_plot_path}")

if __name__ == "__main__":
    main()